version: '3.8'

services:
  
  # Contenedor de la aplicacion de flask
  app:
    build: ./app
    container_name: network-dashboard-app
    restart: always
    expose:
      - "5000"
  
  # Contenedor de Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: network-dashboard-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app