# Nginx actúa como reverse proxy
# Recibe peticiones en el puerto 80 y las reenvía a Flask en el puerto 5000

events {}

http {
    server {
        # Nginx escucha en el puerto 80 
        listen 80;

        location / {
            # Reenvía todo el tráfico a Flask
            proxy_pass http://app:5000;

            # Headers necesarios para que Flask sepa la IP real del cliente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}